"""add paid_by column to transactions

Revision ID: 2a1c723429f9
Revises: 8deac54f00e1
Create Date: 2025-06-29 22:28:22.961359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1c723429f9'
down_revision: Union[str, None] = '8deac54f00e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['paid_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'paid_by')
    # ### end Alembic commands ###
