"""add_archived_and_deleted_transactions_tables

Revision ID: 7a02de1fa524
Revises: 6cac26bf9504
Create Date: 2025-06-30 23:24:35.655330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a02de1fa524'
down_revision: Union[str, None] = '6cac26bf9504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
